const Flags = {
  MAX_TOLERANCE_LEVEL: 20,
  MAX_MORALSHIFTER_LEVEL: 10,
  MAX_DESIRES_LEVEL: 10,
  MAX_ENDURANCE_LEVEL: 10,
  MAX_MYSTICALITY_LEVEL: 10,
  MAX_WISDOM_LEVEL: 5,
  MAX_FORTUNE_LEVEL: -1, //no max level
  MAX_VIRILITY_LEVEL: 15,
  MAX_FERTILITY_LEVEL: 15,
  NEW_GAME_PLUS_RESET_CLIT_LENGTH_MAX: 1.5,
  NEW_GAME_PLUS_LEVEL: 0,
  NEW_GAME_PLUS_BONUS_STORED_XP: 0,
  NEW_GAME_PLUS_BONUS_STORED_ITEMS: null,
  INGNAM_WEAPONSMITH_TALKED: 0,
  INGNAM_ALCHEMIST_TALKED: 0,
  INGNAM_BLACKMARKET_TALKED: 0,
  INGNAM_RUMORS: 0
};

export default Flags;
